apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: prow-jobs-scraper
objects:
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: prow-jobs-scraper
  spec:
    schedule: ${PROW_JOBS_SCRAPER_SCHEDULE}
    suspend: ${{PROW_JOBS_SCRAPER_SUSPEND}}
    jobTemplate:
      spec:
        ttlSecondsAfterFinished: 10800 # keep last 3 runs (3 * 1h)
        backoffLimit: 3
        template:
          spec:
            restartPolicy: OnFailure
            serviceAccountName: assisted-service
            containers:
            - name: prow-jobs-scraper
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              command: 
              - prow-jobs-scraper
              resources:
                limits:
                  cpu: 500m
                  memory: 2000Mi
                requests:
                  cpu: 300m
                  memory: 400Mi
              env:
              - name: LOG_LEVEL
                value: "${PROW_JOBS_SCRAPER_LOG_LEVEL}"
              - name: ES_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-elasticsearch
              - name: ES_STEP_INDEX
                value: "${ES_STEP_INDEX}"
              - name: ES_JOB_INDEX
                value: "${ES_JOB_INDEX}"
              - name: JOB_LIST_URL
                value: "${JOB_LIST_URL}"
              - name: ES_USER
                valueFrom:
                  secretKeyRef:
                    key: master_user_name
                    name: elastic-master-credentials
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: master_user_password
                    name: elastic-master-credentials
- apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: jobs-auto-report
  spec:
    schedule: ${JOBS_AUTO_REPORT_SCHEDULE}
    suspend: ${{JOBS_AUTO_REPORT_SUSPEND}}
    jobTemplate:
      spec:
        ttlSecondsAfterFinished: 10800 # keep last 3 runs (3 * 1h)
        backoffLimit: 3
        template:
          spec:
            restartPolicy: OnFailure
            serviceAccountName: assisted-service
            containers:
            - name: jobs-auto-report
              image: ${IMAGE_NAME}:${IMAGE_TAG}
              imagePullPolicy: ${IMAGE_PULL_POLICY}
              command: 
              - jobs-auto-report
              resources:
                limits:
                  cpu: 500m
                  memory: 2000Mi
                requests:
                  cpu: 300m
                  memory: 400Mi
              env:
              - name: LOG_LEVEL
                value: "${JOBS_AUTO_REPORT_LOG_LEVEL}"
              - name: ES_URL
                valueFrom:
                  secretKeyRef:
                    key: endpoint
                    name: assisted-installer-elasticsearch
              - name: ES_JOB_INDEX
                value: "${ES_JOB_INDEX}"
              - name: ES_USER
                valueFrom:
                  secretKeyRef:
                    key: master_user_name
                    name: elastic-master-credentials
              - name: ES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: master_user_password
                    name: elastic-master-credentials
              - name: SLACK_WEBHOOK_URL
                valueFrom:
                  secretKeyRef:
                    key: ${JOBS_AUTO_REPORT_WEBHOOK_SECRET_KEY}
                    name: ${JOBS_AUTO_REPORT_WEBHOOK_SECRET_NAME}
parameters:
- name: IMAGE_NAME
  value: "quay.io/app-sre/prow-jobs-scraper"
- name: IMAGE_TAG
  required: true
- name: ES_STEP_INDEX
  value: "steps"
- name: ES_JOB_INDEX
  value: "jobs"
- name: JOB_LIST_URL
  value: "https://prow.ci.openshift.org/prowjobs.js?omit=annotations,decoration_config,pod_spec"
- name: PROW_JOBS_SCRAPER_LOG_LEVEL
  value: "INFO"
- name: IMAGE_PULL_POLICY
  value: "Always"
- name: PROW_JOBS_SCRAPER_SUSPEND
  value: "false"
- name: PROW_JOBS_SCRAPER_SCHEDULE
  value: "@hourly"
- name: JOBS_AUTO_REPORT_LOG_LEVEL
  value: "INFO"
- name: JOBS_AUTO_REPORT_SUSPEND
  value: "true"
- name: JOBS_AUTO_REPORT_SCHEDULE
  value: "@weekly"
- name: JOBS_AUTO_REPORT_WEBHOOK_SECRET_KEY
  value: webhook_url
- name: JOBS_AUTO_REPORT_WEBHOOK_SECRET_NAME
  value: jobs-auto-report-slack-webhook
